"""
EuroMLions — Update Script (Orchestrator)

Called by GitHub Actions on schedule. Determines what to do
based on the --mode flag:

  --mode predict   Pre-draw: generate predictions for tonight's draw
  --mode compare   Post-draw: fetch actual results, compare to predictions
  --mode auto      Detect mode based on current day/time (default)

Also generates a summary for email notifications.
"""

import argparse
import json
import os
import sys
from datetime import datetime

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'models'))

DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
SUMMARY_PATH = os.path.join(DATA_DIR, 'email-summary.html')
PREDICTIONS_PATH = os.path.join(DATA_DIR, 'predictions.json')
HISTORY_PATH = os.path.join(DATA_DIR, 'history-predictions.json')


def run_predict():
    """Pre-draw: generate predictions."""
    from predict import generate_predictions
    output = generate_predictions()
    generate_predict_email(output)
    return output


def run_compare():
    """Post-draw: fetch results and compare."""
    from fetch_results import main as fetch_main
    latest = fetch_main()

    if latest is None:
        print("✗ Could not fetch results")
        generate_error_email("Could not fetch draw results from the National Lottery site.")
        return None

    generate_compare_email(latest)
    return latest


def detect_mode():
    """Auto-detect whether this is a pre-draw or post-draw run."""
    now = datetime.now()
    day = now.weekday()

    # Tuesday (1) or Friday (4) = pre-draw (predict)
    if day in [1, 4]:
        return 'predict'
    # Wednesday (2) or Saturday (5) = post-draw (compare)
    elif day in [2, 5]:
        return 'compare'
    else:
        print(f"Today is {now.strftime('%A')} — not a scheduled run day.")
        print("Use --mode predict or --mode compare to run manually.")
        return None


# ─── Email Generation ─────────────────────────────────────────

def generate_predict_email(output):
    """Generate pre-draw email: here are tonight's predictions."""
    ens = output.get('ensemble', {})
    main = ens.get('main_numbers', [])
    stars = ens.get('lucky_stars', [])
    next_draw = output.get('next_draw', 'tonight')

    main_str = ' - '.join(str(n) for n in main)
    stars_str = ' - '.join(str(n) for n in stars)

    html = f"""
    <div style="font-family: -apple-system, sans-serif; max-width: 500px; margin: 0 auto; padding: 20px;">
      <h1 style="text-align: center; color: #ffd700;">🎰 EuroMLions</h1>
      <h2 style="text-align: center; color: #333;">Predictions for {next_draw}</h2>

      <div style="background: #1a2332; border-radius: 12px; padding: 24px; text-align: center; margin: 20px 0;">
        <p style="color: #8b93a8; margin: 0 0 12px 0; font-size: 14px;">MAIN NUMBERS</p>
        <p style="color: #fff; font-size: 28px; font-weight: 700; margin: 0; letter-spacing: 4px;">
          {main_str}
        </p>
        <p style="color: #8b93a8; margin: 16px 0 8px 0; font-size: 14px;">LUCKY STARS</p>
        <p style="color: #ffd700; font-size: 28px; font-weight: 700; margin: 0; letter-spacing: 4px;">
          {stars_str}
        </p>
      </div>

      <p style="color: #666; font-size: 13px; text-align: center;">
        Generated by three LSTM neural networks.<br>
        Confidently wrong since 2026. 💙
      </p>
    </div>
    """

    with open(SUMMARY_PATH, 'w') as f:
        f.write(html)
    print(f"✓ Email summary saved to {SUMMARY_PATH}")


def generate_compare_email(latest):
    """Generate post-draw email: here's how we did."""
    if not os.path.exists(HISTORY_PATH):
        return

    with open(HISTORY_PATH, 'r') as f:
        history = json.load(f)

    # Find the most recently completed entry
    completed = [h for h in history if h['actual_main'] is not None]
    if not completed:
        return

    entry = completed[-1]
    main_matched = entry.get('main_matched', 0)
    stars_matched = entry.get('stars_matched', 0)

    ens = entry.get('ensemble', {})
    mA = entry.get('model_A', {})
    mB = entry.get('model_B', {})
    mC = entry.get('model_C', {})

    ens_main = ', '.join(str(n) for n in ens.get('main', []))
    ens_stars = ', '.join(str(n) for n in ens.get('stars', []))
    mA_main = ', '.join(str(n) for n in mA.get('main', []))
    mA_stars = ', '.join(str(n) for n in mA.get('stars', []))
    mB_main = ', '.join(str(n) for n in mB.get('main', []))
    mC_stars = ', '.join(str(n) for n in mC.get('stars', []))
    actual_main = ', '.join(str(n) for n in entry['actual_main'])
    actual_stars = ', '.join(str(n) for n in entry['actual_stars'])

    # Determine result emoji
    if main_matched >= 3:
        emoji = '🎉'
        msg = 'Not bad at all!'
    elif main_matched >= 1 or stars_matched >= 1:
        emoji = '🤏'
        msg = 'Close-ish. We take those.'
    else:
        emoji = '😅'
        msg = 'Confidently wrong, as promised.'

    total_completed = len(completed)
    avg_main = sum(h.get('main_matched', 0) for h in completed) / total_completed
    avg_stars = sum(h.get('stars_matched', 0) for h in completed) / total_completed

    html = f"""
    <div style="font-family: -apple-system, sans-serif; max-width: 500px; margin: 0 auto; padding: 20px;">
      <h1 style="text-align: center; color: #ffd700;">🎰 EuroMLions</h1>
      <h2 style="text-align: center; color: #333;">Draw Results — {entry['draw_date']}</h2>

      <div style="background: #1a2332; border-radius: 12px; padding: 24px; margin: 20px 0;">
        <table style="width: 100%; color: #fff; font-size: 14px; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; color: #8b93a8;">Ensemble</td>
            <td style="padding: 8px; font-weight: 600;">{ens_main} + {ens_stars}</td>
          </tr>
          <tr>
            <td style="padding: 8px; color: #8b93a8; font-size: 12px;">Model A</td>
            <td style="padding: 4px 8px; font-size: 12px; color: #ccc;">{mA_main} + {mA_stars}</td>
          </tr>
          <tr>
            <td style="padding: 8px; color: #8b93a8; font-size: 12px;">Model B</td>
            <td style="padding: 4px 8px; font-size: 12px; color: #ccc;">{mB_main}</td>
          </tr>
          <tr>
            <td style="padding: 8px; color: #8b93a8; font-size: 12px;">Model C</td>
            <td style="padding: 4px 8px; font-size: 12px; color: #ccc;">{mC_stars}</td>
          </tr>
          <tr>
            <td style="padding: 8px; color: #8b93a8;">Actual</td>
            <td style="padding: 8px; font-weight: 600;">{actual_main} + {actual_stars}</td>
          </tr>
          <tr style="border-top: 1px solid #2a3442;">
            <td style="padding: 12px 8px; color: #8b93a8;">Result</td>
            <td style="padding: 12px 8px; font-weight: 700; font-size: 18px; color: #ffd700;">
              {emoji} {main_matched}/5 main, {stars_matched}/2 stars
            </td>
          </tr>
        </table>
      </div>

      <p style="text-align: center; color: #333; font-size: 15px; font-weight: 600;">
        {msg}
      </p>

      <div style="background: #f5f5f5; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <p style="color: #666; font-size: 13px; margin: 0;">
          <strong>Running stats:</strong> {total_completed} draws tracked |
          Avg {avg_main:.2f}/5 main | Avg {avg_stars:.2f}/2 stars<br>
          Random baseline: 0.50/5 main, 0.33/2 stars
        </p>
      </div>

      <p style="color: #999; font-size: 12px; text-align: center;">
        EuroMLions — predicting EuroMillions with ML since 2026 🍀
      </p>
    </div>
    """

    with open(SUMMARY_PATH, 'w') as f:
        f.write(html)
    print(f"✓ Email summary saved to {SUMMARY_PATH}")


def generate_error_email(error_msg):
    """Generate error email when something goes wrong."""
    html = f"""
    <div style="font-family: -apple-system, sans-serif; max-width: 500px; margin: 0 auto; padding: 20px;">
      <h1 style="text-align: center;">🎰 EuroMLions — Error</h1>
      <p style="color: #e74c3c; text-align: center;">{error_msg}</p>
      <p style="color: #666; font-size: 13px; text-align: center;">Check the GitHub Actions logs for details.</p>
    </div>
    """
    with open(SUMMARY_PATH, 'w') as f:
        f.write(html)


# ─── Main ─────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='EuroMLions Update')
    parser.add_argument(
        '--mode', choices=['predict', 'compare', 'auto'], default='auto',
        help='predict = generate predictions, compare = fetch results and compare, '
             'auto = detect from current day',
    )
    args = parser.parse_args()

    print("=" * 50)
    print("EuroMLions — Update")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 50)

    mode = args.mode
    if mode == 'auto':
        mode = detect_mode()
        if mode is None:
            return

    print(f"\nMode: {mode}\n")

    if mode == 'predict':
        run_predict()
    elif mode == 'compare':
        run_compare()

    print("\n✓ Update complete")


if __name__ == '__main__':
    main()
